### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Liqxid** [trenchkid/lord#2]
Is there a nitro sniper, perhaps one that you can set on or off?

**Comment by trenchkid** [comment]
i'll add that if u want or you could use my homies selfbot. https://github.com/devil-xin/genesis 
its in py so it will snipe faster

**Comment by Liqxid** [comment]
> i'll add that if u want or you could use my homies selfbot. https://github.com/devil-xin/genesis 
> 
> its in py so it will snipe faster

Yeah if you can please add it where you can toggle, I prefer js and I like the design of this selfbot. Also if you can giveaway snipe that you can toggle too!

**Comment by Liqxid** [comment]
> i'll add that if u want or you could use my homies selfbot. https://github.com/devil-xin/genesis 
> 
> its in py so it will snipe faster

Please respond back when you made it

**Comment by trenchkid** [comment]
> Yeah if you can please add it where you can toggle, I prefer js and I like the design of this selfbot. Also if you can giveaway snipe that you can toggle too!

I'll add that today

**Comment by Liqxid** [comment]
> > Yeah if you can please add it where you can toggle, I prefer js and I like the design of this selfbot. Also if you can giveaway snipe that you can toggle too!
> 
> 
> 
> I'll add that today

Thank you!

**Comment by trenchkid** [comment]
Added the giveaway sniper and nitro sniper!
I'll add toggling later today but yh, just reinstall everything, and insert your token and prefix in the config.json
